### ISSUE TITLE
won't run in Win10 :/

### ISSUE THREAD

**Issue by tomByrer** [luwes/js-diff-benchmark#34]
```bash
$ npm test

> js-diff-benchmark@1.0.0 test D:\doc\prog\learn\js\vdom\js-diff-benchmark
> node --expose-gc src/bench.js

D:\doc\prog\learn\js\vdom\js-diff-benchmark\src\utils.js:29
    mutations.push(`remove: drop(${oldNode.textContent})`);
                                           ^

TypeError: Cannot read property 'textContent' of undefined
    at Dommy.container.removeChild (D:\doc\prog\learn\js\vdom\js-diff-benchmark\src\utils.js:29:44)
    at module.exports (D:\doc\prog\learn\js\vdom\js-diff-benchmark\libs\spect.js:20:18)       
    at create1000 (D:\doc\prog\learn\js\vdom\js-diff-benchmark\src\utils.js:82:14)
    at D:\doc\prog\learn\js\vdom\js-diff-benchmark\src\bench.js:75:20
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\doc\prog\learn\js\vdom\js-diff-benchmark\src\bench.js:58:6)     
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
```
TY :)

**Comment by luwes** [comment]
thanks for reporting @tomByrer 
I can't think right away what it could be
